version: '3'

services:
  db:
    image: mysql:8
    container_name: test-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test-db
      MYSQL_USER: user
      MYSQL_PASSWORD: ppassword
      TZ: Asia/Tokyo
    ports:
      - 3307:3307
    tmpfs:
      - /var/lib/mysql
    volumes:
      - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf